BaseURL = "http://blog.wada811.com"
LanguageCode = "ja-JP"
Title = "wada811/blog"

[Params]
    Author = "wada811"
    DateForm = "2006-01-02" # time - The Go Programming Language http://golang.org/pkg/time/#Time.Format
    Facebook = "takumi.wada.92"
    Twitter = "wada811"
    Github = "wada811"
    SyntaxHighlightTheme = "solarized_dark.min.css"

[Indexes]
    tag = "tags"

[Permalinks]
    post = "/:section/:filename/"